version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: # runs not using Workflows must have a `build` job as entry point 
    docker: # run the steps with Docker
      - image: python:3.7.3-stretch
      
    working_directory: ~/repo
      
    steps: # steps that comprise the `build` job
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
          
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64" &&\
                chmod +x /bin/hadolint
      
      - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
      - run:
          name: run lint
          command: | 
            . venv/bin/activate
            make lint
